### ISSUE TITLE
upload code file for others to fix bugs

### ISSUE THREAD

**Issue by PatrickRBailey** [pwilkins05/17AssignD#1]

**Comment by Nestoring1** [comment]
Uploaded mine, I'll be waiting for others to upload because I have no knowledge to fix your JavaScript program.

**Comment by PatrickRBailey** [comment]
lol One of my bugs is literally calling a function.

**Comment by Nestoring1** [comment]
That's the only thing that made sense to, I didn't do it because I thought I had to fix all of the code.

**Comment by PatrickRBailey** [comment]
No it's just fix one bug
